default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: password

development:
  <<: *default
  database: rails_budget_app_development
  username: postgres
  password: password

test:
  <<: *default
  database: rails_budget_app_test
  username: postgres
  password: password

production:
  <<: *default
  database: rails_budget_app_production
  username: rails_budget_app
  password: <%= ENV["RAILS_BUDGET_APP_DATABASE_PASSWORD"] %>
